<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_63ee46b7377a4',
	'title' => 'Taxonomies Fields',
	'fields' => array(
		array(
			'key' => 'field_63ee46c7f3e86',
			'label' => 'Taxonomy Keywords',
			'name' => 'taxonomy_keywords',
			'type' => 'text',
			'instructions' => 'Separate Keywords by comma.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'show_column' => 0,
			'show_column_sortable' => 0,
			'show_column_weight' => 1000,
			'allow_quickedit' => 0,
			'allow_bulkedit' => 0,
		),
		array(
			'key' => 'field_63f74210f11ee',
			'label' => 'Αφιερωματικό Tag Name',
			'name' => 'taxonomy_tag_name',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'show_column' => 0,
			'show_column_sortable' => 0,
			'show_column_weight' => 1000,
			'allow_quickedit' => 0,
			'allow_bulkedit' => 0,
		),
		array(
			'key' => 'field_63f74210e64dc',
			'label' => 'Αφιερωματικό Tag',
			'name' => 'taxonomy_tagsection',
			'type' => 'text',
			'instructions' => 'Βαζουμε το slug σκετο. Πχ: kina-rosia',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'show_column' => 0,
			'show_column_sortable' => 0,
			'show_column_weight' => 1000,
			'allow_quickedit' => 0,
			'allow_bulkedit' => 0,
		),

		array(
			'key' => 'field_63f74210r22ee',
			'label' => 'Μαθ. Εφημερίδα Τιτλος',
			'name' => 'taxonomy_math_name',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'show_column' => 0,
			'show_column_sortable' => 0,
			'show_column_weight' => 1000,
			'allow_quickedit' => 0,
			'allow_bulkedit' => 0,
		),
		array(
			'key' => 'field_63f74210ed44ee',
			'label' => 'Μαθ. Εφημερίδα Shortcode',
			'name' => 'taxonomy_math_shr',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'show_column' => 0,
			'show_column_sortable' => 0,
			'show_column_weight' => 1000,
			'allow_quickedit' => 0,
			'allow_bulkedit' => 0,
		),		

	),
	'location' => array(
		array(
			array(
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'category',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;

/* DATE AND PDF TEXT */
acf_add_local_field_group(array(
	'key' => 'group_5b31eeb9195c0',
	'title' => 'Πεδία Kιόσκι',
	'fields' => array(
		array(
			'key' => 'field_5b31eec170919',
			'label' => 'Ημερομηνία',
			'name' => 'kioski_date',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_5b64266601828',
			'label' => 'PDF SHORTCODE',
			'name' => 'tanea__pdf_shortcode',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'shortcode',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'show_column' => 0,
			'show_column_sortable' => 0,
			'show_column_weight' => 1000,
			'allow_quickedit' => 0,
			'allow_bulkedit' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'kioski_posts',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
		1 => 'excerpt',
		2 => 'discussion',
		3 => 'comments',
		4 => 'revisions',
		5 => 'slug',
		6 => 'author',
		7 => 'format',
		8 => 'page_attributes',
		9 => 'categories',
		10 => 'tags',
		11 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
));




/* AUTHOR EXTRA FIELDS */
acf_add_local_field_group(array(
	'key' => 'group_5a9590182d955',
	'title' => 'Extra Authors Fields',
	'fields' => array(
		array(
			'key' => 'field_5a959026942b1',
			'label' => 'Ιδιότητα',
			'name' => 'author-desc',
			'type' => 'text',
			'instructions' => 'Παρακαλώ συμπληρώστε την ειδικότητα / ιδιότητα του αρθρογράφου',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5aa41fb3de8e0',
			'label' => 'Εικόνα αρθρογράφου',
			'name' => 'author-image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'user_form',
				'operator' => '==',
				'value' => 'all',
			),
		),
		array(
			array(
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'nea_authors',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));





acf_add_local_field_group(array(
	'key' => 'group_5b6e893897785',
	'title' => 'Attachment ID',
	'fields' => array(
		array(
			'key' => 'field_5b6e89403c38e',
			'label' => 'Attachment ID',
			'name' => 'attachment_id',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'attachment',
				'operator' => '==',
				'value' => 'all',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5a745e41546d0',
	'title' => 'Extra Posts Fields',
	'fields' => array(
		array(
			'key' => 'field_5a745e4c0e37d',
			'label' => 'OLD ID',
			'name' => 'old_id',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5a745f6f6a1a7',
			'label' => 'OLD Slug',
			'name' => 'old_slug',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5a9591806a5fe',
			'label' => 'Subtitle',
			'name' => 'post__subtitle',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
//		array(
//			array(
//				'param' => 'post_type',
//				'operator' => '==',
//				'value' => 'page',
//			),
//		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 0,
	'description' => '',
));



acf_add_local_field_group(array(
	'key' => 'group_5a801a9f11e08',
	'title' => 'Πεδία σύνταξης',
	'fields' => array(
    
// 		array(
// 			'key' => 'field_5a801ac4e0saasd8',
// 			'label' => 'Ονομα συνεντευξιαζόμενου',
// 			'name' => 'named_tile',
// 			'type' => 'text',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 			'prepend' => '',
// 			'append' => '',
// 			'maxlength' => '',
// 		),
        
		array(
			'key' => 'field_5a801ac4e2qqqtd1',
			'label' => 'Εμπορικός τίτλος',
			'name' => 'front_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		), 
		array(
			'key' => 'field_5a801ac4e2qqxxe2',
			'label' => 'Εμπορικό Lead',
			'name' => 'front_lead',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5a801bg1b1b2e',
			'label' => 'Εξωτερικός Αρθρογράφος',
			'name' => 'exauthor_textn',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),		
		array(
			'key' => 'field_618804b895f1a',
			'label' => 'Editor',
			'name' => 'editor',
			'type' => 'taxonomy',
			'instructions' => 'Επιλέγουμε σε περίπτωση που θέλουμε το άρθρο να έχει υπογραφή.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'nea_authors',
			'field_type' => 'multi_select',
			'allow_null' => 1,
			'add_term' => 0,
			'save_terms' => 1,
			'load_terms' => 1,
			'return_format' => 'object',
			'multiple' => 0,
		),
		array(
			'key' => 'field_618804b222t4a',
			'label' => 'Tags αρθρου',
			'name' => 'posttags',
			'type' => 'taxonomy',
			'instructions' => 'Προσθηκη Tags',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'post_tag',
			'field_type' => 'multi_select',
			'allow_null' => 1,
			'add_term' => 0,
			'save_terms' => 1,
			'load_terms' => 1,
			'return_format' => 'object',
			'multiple' => 0,
		),    
		array(
			'key' => 'field_5a801ac4e2f2e',
			'label' => 'Βινιέτα / Υπέρτιτλος',
			'name' => 'hypertext',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),

		array(
			'key' => 'field_5a801ac4q1trw',
			'label' => 'Video URL',
			'name' => 'postvideo_url',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),    
    
		array(
			'key' => 'field_5a916b9e35bb6',
			'label' => 'Ημερομηνία / Ωρα Ενημέρωσης',
			'name' => 'scondtimedate',
			'type' => 'date_time_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'j F Y, H:i',
			'return_format' => 'j F Y, H:i',
			'first_day' => 1,
		),
// 		array(
// 			'key' => 'field_5aa173a691519',
// 			'label' => 'Keywords',
// 			'name' => 'meta__keywords',
// 			'type' => 'text',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 			'prepend' => '',
// 			'append' => '',
// 			'maxlength' => '',
// 		),
// 		array(
// 			'key' => 'field_5aa3bbee1c45c',
// 			'label' => 'Απόκρυψη συντάκτη',
// 			'name' => 'authorsec',
// 			'type' => 'select',
// 			'instructions' => 'Αν επιλέξετε ΟΧΙ, δηλαδη να εμφανιστεί ο συντάκτης θα πρέπει να τον αποδώσετε στο κουτάκι συντάκτης.',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'choices' => array(
// 				'yes' => 'NAI',
// 				'no' => 'OXI',
// 			),
// 			'default_value' => array(
// 			),
// 			'allow_null' => 1,
// 			'multiple' => 0,
// 			'ui' => 0,
// 			'ajax' => 0,
// 			'return_format' => 'value',
// 			'placeholder' => '',
// 		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'printed_post',
			),
		),       
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5aa460afa03b2',
	'title' => 'Video Groups',
	'fields' => array(
		array(
			'key' => 'field_5a801ab1e0f1d',
			'label' => 'Διάρκεια Video',
			'name' => 'videopost_time',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '00:00',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
//		array(
//			'key' => 'field_5a8087d0c24f1',
//			'label' => 'Youtube Player',
//			'name' => 'youtube_player',
//			'type' => 'oembed',
//			'instructions' => 'Παρακαλώ οπως βάλετε ένα κώδικα youtube',
//			'required' => 0,
//			'conditional_logic' => 0,
//			'wrapper' => array(
//				'width' => '',
//				'class' => '',
//				'id' => '',
//			),
//			'width' => '',
//			'height' => '',
//		),
//		array(
//			'key' => 'field_5a9811cfd3023',
//			'label' => 'Facebook Player',
//			'name' => 'facebook_player',
//			'type' => 'oembed',
//			'instructions' => 'Παρακαλώ όπως τοποθετήσετε κώδικα facebook',
//			'required' => 0,
//			'conditional_logic' => 0,
//			'wrapper' => array(
//				'width' => '',
//				'class' => '',
//				'id' => '',
//			),
//			'width' => '',
//			'height' => '',
//		),
//		array(
//			'key' => 'field_5a9da5b05bdd2',
//			'label' => 'TOBHMA Native Video',
//			'name' => 'extra_video',
//			'type' => 'text',
//			'instructions' => '',
//			'required' => 0,
//			'conditional_logic' => 0,
//			'wrapper' => array(
//				'width' => '',
//				'class' => '',
//				'id' => '',
//			),
//			'default_value' => '',
//			'placeholder' => '',
//			'prepend' => '',
//			'append' => '',
//			'maxlength' => '',
//		),
//		array(
//			'key' => 'field_5aa3e8699c4d4',
//			'label' => 'TOBHMA Native Video Mobile App',
//			'name' => 'extra_video_mobile_app',
//			'type' => 'oembed',
//			'instructions' => 'Please paste a JwPlayer video iframe.',
//			'required' => 0,
//			'conditional_logic' => 0,
//			'wrapper' => array(
//				'width' => '',
//				'class' => '',
//				'id' => '',
//			),
//			'width' => '',
//			'height' => '',
//		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 0,
	'description' => '',
));


acf_add_local_field_group(array(
	'key' => 'group_5a9703f870ad6',
	'title' => 'TOBHMA Photo Repeater',
	'fields' => array(
		array(
			'key' => 'field_5a970405e2c2f',
			'label' => 'Gallery Repeater',
			'name' => 'ingr_repeater',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Προσθήκη γραμμής',
			'sub_fields' => array(
				array(
					'key' => 'field_5a97041fe2c30',
					'label' => 'Image Field',
					'name' => 'ingr_image_field',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5a970430e2c31',
					'label' => 'Image Title',
					'name' => 'ingr_image_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5a970445e2c32',
					'label' => 'Image Credit',
					'name' => 'ingr_image_credit',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'printed_post',
			),
		),    
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 0,
	'description' => '',
));


acf_add_local_field_group(array(
	'key' => 'group_5aa1b49w1r789',
	'title' => 'Κάθετη εικόνα',
	'fields' => array(
		array(
			'key' => 'field_5aa1b4e666688',
			'label' => 'Κάθετη εικόνα',
			'name' => 'vertical_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'printed_post',
			),
		),    
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

?>