<?php if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_62e923b009a01',
	'title' => 'Must Read Repeater',
	'fields' => array(
		array(
			'key' => 'field_62e923b8c1acc',
			'label' => 'Must read Repearer',
			'name' => 'must_read_repearer',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_62e923eac1acd',
			'min' => 6,
			'max' => 6,
			'layout' => 'table',
			'button_label' => 'Προσθήκη άρθρου',
			'sub_fields' => array(
				array(
					'key' => 'field_62e923eac1acd',
					'label' => 'Τίτλος άρθρου',
					'name' => 'mr_rpt_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_62e92413c1ace',
					'label' => 'Link άρθρου',
					'name' => 'mr_rpt_link',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_62e92429c1acf',
					'label' => 'Εικόνα άρθρου',
					'name' => 'mr_rpt_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_62e92446c1ad0',
					'label' => 'Επιλογή Brand',
					'name' => 'mr_rpt_brand',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'ot' => 'OT',
// 						'tovima' => 'TO BHMA',
						'tanea' => 'TA NEA',
						'imommy' => 'IMOMMY',
						'vita' => 'VITA',
						'mega' => 'MEGA',
						'ingr' => 'IN',
						'shopflix' => 'SHOPFLIX',
// 						'to10' => 'TO10',
// 						'bscience' => 'BSCIENCE',
					),
					'default_value' => false,
					'allow_null' => 1,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_62e923eac3rtx',
					'label' => 'Χρωμα color',
					'name' => 'mr_rpt_text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),         
				array(
					'key' => 'field_62e923eac2xxe',
					'label' => 'Χρωμα Background',
					'name' => 'mr_rpt_bgx',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
      array(
        'key' => 'field_64667c509ee66',
        'label' => 'Feed Art',
        'name' => 'mr_rpt_row',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'ui' => 0,
        'ui_on_text' => '',
        'ui_off_text' => '',
      ),        
        
        
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'external_posts',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;
?>